[[fields-bitfield]]
=== &lt;bitfield&gt; Field ===
The **&lt;bitfield&gt;** is a container field, which allows wrapped member fields
to be serialized using limited number of bits (instead of bytes). 
The supported fields, that can be members of the **&lt;bitfield&gt;**, are:

* <<fields-enum, &lt;enum&gt; >>
* <<fields-int, &lt;int&gt; >>
* <<fields-set, &lt;set&gt; >>

Since **v2** of the specification it is also allowed to use 
<<fields-ref, &lt;ref&gt; >> field, which references one of the field types above.

The **&lt;bitfield&gt;** field has all the <<fields-common, common>> properties
as well as extra properties and elements described below.

[[fields-bitfield-member-fields]]
==== Member Fields ====
Member fields need to be listed as children XML elements of the **&lt;bitfield&gt;**.
Every such member is expected to use **bitLength** property to specify its
serialization length **in bits**. If it is not specified, then length in bits
is calculated automatically as length **in bytes** multiplied by **8**.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema name="MyProtocol" endian="big">
    <fields>
        <bitfield name="SomeBitfield">
            <int name="SomeIntMember" type="uint8" bitLength="3" />
            <set name="SomeSetMember" bitLength="3">
                ...
            </set>
            <enum name="SomeEnumMember" type="uint8" bitLength="2">
                ...
            </enum>
        </bitfield>
    </fields>
</schema>
----
**NOTE** that summary of all the lengths in bits of all the members must be
divisible by **8** and mustn't exceed **64** bits, otherwise the code generator 
must report an error.

The members of **&lt;bitfield&gt;** must be listed in order starting from the
**least** significant bit. In the example above *SomeIntMember* occupies bits
[0 - 2], *SomeSetMember* occupies bits [3 - 5], and *SomeEnumMember* occupies
bits [6 -7].

If there is any other <<intro-properties, property>> defined as XML child
of the **&lt;bitfield&gt;**, then all the members must be wrapped in 
**&lt;members&gt;** XML element for separation.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema name="MyProtocol" endian="big">
    <fields>
        <bitfield name="SomeBitfield">
            <displayName value="Proper Bitfield Name" />
            <members>
                <int name="SomeIntMember" type="uint8" bitLength="3" />
                <set name="SomeSetMember" bitLength="3">
                    ...
                </set>
                <enum name="SomeEnumMember" type="uint8" bitLength="2">
                    ...
                </enum>
            </members>
        </bitfield>
    </fields>
</schema>
----

[[fields-bitfield-endian]]
==== Endian ====
When serializing, the **&lt;bitfield&gt;** object needs to combine the
values of all the members into single unsigned raw value of appropriate length,
and write the received value using appropriate endian.
By default **endian** of the <<schema-schema, schema>> is used, unless it
is overridden using extra **endian** property of the **&lt;bitfield&gt;** field.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema name="MyProtocol" endian="big">
    <fields>
        <bitfield name="SomeBitfield" endian="little">
            ...
        </bitfield>
    </fields>
</schema>
----

[[fields-bitfield-replacing-member-fields]]
==== Replacing Member Fields ====
It is possible to replace some of the copied member fields after 
<<fields-common-reusing-other-fields, reuse>> using **&lt;replace&gt;**
child node, which wraps the replacing fields.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema name="MyProtocol" endian="big">
    <fields>
        <bitfield name="SomeBitfield" endian="little">
            <int name="Mem1" type="uint8" bitLength="4" />
            <enum name="Mem2" type="uint8" bitLength="4">
                <validValue name="V0" val="0" />
                <validValue name="V1" val="1" />
            </enum>
        </bitfield>
        
        <bitfield name="SomeOtherBitfield" reuse="SomeBitfield">
            <replace>
                <set name="Mem2" type="uint8" bitLength="4">
                    <bit name="B0" idx="0" />
                    <bit name="B1" idx="1" />
                </set>
            </replace>
        </bitfield>
    </fields>
</schema>
----
The replacing field must have the same name as the reused member field it is
replacing. The **&lt;replace&gt;** child node may have multiple member fields replacing
the copied ones. The order of the fields inside the **&lt;replace&gt;** child node
is not important, the order of the fields is determined by the original 
**&lt;bitfield&gt;** field, which was <<fields-common-reusing-other-fields, reused>>.

The example above is equivalent to defining `SomeOtherBitfield` **&lt;bitfield&gt;** field
in the following way.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema name="MyProtocol" endian="big">
    <fields>
        <bitfield name="SomeOtherBitfield">
            <int name="Mem1" type="uint8" bitLength="4" />
            <set name="Mem2" type="uint8" bitLength="4">
                <bit name="B0" idx="0" />
                <bit name="B1" idx="1" />
            </set>
        </bitfield>
    </fields>
</schema>
----

Use <<appendix-bitfield, properties table>> for future references.
