[[fields-bundle]]
=== &lt;bundle&gt; Field ===
The **&lt;bundle&gt;** is a container field, which aggregates multiple 
independent fields (of any kind) into a single one. 
The **&lt;bundle&gt;** field has all the <<fields-common, common>> properties.

==== Member Fields ====
Member fields need to be listed as children XML elements of the **&lt;bundle&gt;**.
[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema name="MyProtocol" endian="big">
    <fields>
        <bundle name="SomeBundle">
            <int name="SomeIntMember" type="uint8" />
            <set name="SomeSetMember" length="1">
                ...
            </set>
            <enum name="SomeEnumMember" type="uint8">
                ...
            </enum>
            <bundle name="SomeInnerBundle">
                ...
            </bundle>
        </bundle>
    </fields>
</schema>
----
If there is any other <<intro-properties, property>> defined as XML child
of the **&lt;bundle&gt;**, then all the members must be wrapped in 
**&lt;members&gt;** XML element for separation.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema name="MyProtocol" endian="big">
    <fields>
        <bundle name="SomeBundle">
            <displayName value="Proper Bundle Name" />
            <members>
                <int name="SomeIntMember" type="uint8" bitLength="3" />
                <set name="SomeSetMember" length="1">
                    ...
                </set>
                <enum name="SomeEnumMember" type="uint8">
                    ...
                </enum>
                <bundle name="SomeInnerBundle">
                    ...
                </bundle>
            </members>
        </bundle>
    </fields>
</schema>
----

[[fields-bundle-reusing-other-bundle]]
==== Reusing Other &lt;bundle&gtp ====
Like any other field, **&lt;bundle&gt;** supports **reuse** of any other **&lt;bundle&gt;**.
Such reuse copies all the fields from original **&lt;bundle&gt;** in addition
to all the properties. Any new defined member field gets **appended** to the copied ones.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema name="MyProtocol" endian="big">
    <fields>
        <bundle name="SomeBundle">
            <int name="F1" type="uint32" />
            <float name="F2" type="float" />
        </bundle>
        
        <bundle name="SomeOtherBundle" reuse="SomeBundle">
            <string name="F3" length="16" />
        </bundle>        
    </fields>
</schema>
----
In the example above *SomeOtherBundle* has **3** member fields: *F1*, *F2*, and *F3*.

[[fields-bundle-replacing-member-fields]]
==== Replacing Member Fields ====
It is possible to replace some of the copied member fields after 
<<fields-common-reusing-other-fields, reuse>> using **&lt;replace&gt;**
child node, which wraps the replacing fields.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema name="MyProtocol" endian="big">
    <fields>
        <bundle name="SomeBundle">
            <int name="Mem1" type="uint8" />
            <enum name="Mem2" type="uint8">
                <validValue name="V0" val="0" />
                <validValue name="V1" val="1" />
            </enum>
        </bundle>
        
        <bundle name="SomeOtherBundle" reuse="SomeBundle">
            <replace>
                <set name="Mem2" type="uint8">
                    <bit name="B0" idx="0" />
                    <bit name="B1" idx="1" />
                </set>
            </replace>
        </bundle>
    </fields>
</schema>
----

The replacing field must have the same name as the reused member field it is
replacing. The **&lt;replace&gt;** child node may have multiple member fields replacing
the copied ones. The order of the fields inside the **&lt;replace&gt;** child node
is not important, the order of the fields is determined by the original 
**&lt;bundle&gt;** field, which was <<fields-common-reusing-other-fields, reused>>.

It is possible to combine **&lt;replace&gt;**-ing copied member fields and extending
the **&lt;bundle&gt;** with new fields. 
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema name="MyProtocol" endian="big">
    <fields>
        <bundle name="SomeBundle">
            <int name="Mem1" type="uint8" />
            <enum name="Mem2" type="uint8">
                <validValue name="V0" val="0" />
                <validValue name="V1" val="1" />
            </enum>
        </bundle>
        
        <bundle name="SomeOtherBundle" reuse="SomeBundle">
            <replace>
                <set name="Mem2" type="uint8">
                    <bit name="B0" idx="0" />
                    <bit name="B1" idx="1" />
                </set>
            </replace>
            <members>
                <int name="Mem3" type="uint16" />
            </members>
        </bundle>
    </fields>
</schema>
----


The example above is equivalent to defining `SomeOtherBundle` **&lt;bundle&gt;** field
in the following way.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema name="MyProtocol" endian="big">
    <fields>
        <bundle name="SomeOtherBundle">
            <int name="Mem1" type="uint8" />
            <set name="Mem2" type="uint8">
                <bit name="B0" idx="0" />
                <bit name="B1" idx="1" />
            </set>
            <int name="Mem3" type="uint16" />
        </bundle>
    </fields>
</schema>
----


[[fields-bundle-alias-names]]
==== Alias Names to Member Fields ====
Sometimes an existing member field may be renamed and/or moved. It is possible to
create alias names for the fields to keep the old client code being able to compile
and work. Please refer to <<aliases-aliases, Aliases>> chapter for more details.

Use <<appendix-bundle, properties table>> for future references.
