[[fields-common]]
=== Common Properties of Fields ===
Every field is different, and defines its own properties and/or other aspects.
However, there are common properties, that are applicable to every field. 
They are summarized below.

[[fields-common-name]]
==== Name ====
Every field must define it's <<intro-names, name>>, which is expected to be 
used by a code generator when defining a relevant class. The name is defined
using **name** <<intro-properties, property>>.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <int name="SomeField" ... />
    </fields>
</schema>
----

[[fields-common-description]]
==== Description ====
It is possible to provide a description of the field about what it is and
how it is expected to be used. This description is only for documentation
purposes and may find it's way into the generated code as a comment for the
generated class. The <<intro-properties, property>> is **description**.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <int name="SomeField" type="uint8">
            <description>
                Some long
                multiline
                description
            </description>
        </int>
    </fields>
</schema>
----

[[fields-common-reusing-other-fields]]
==== Reusing Other Fields ====
Sometimes two different fields are very similar, but differ in one particular
aspect. **CommsDSL** allows copying all the properties from previously defined
field (using **reuse** property) and change some of them after the copy. For example:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <int name="SomeIntField" type="uint8" defaultValue="3" />
        <bitfield name="SomeBitfield">
            <int name="Member1" reuse="SomeIntField" bitLength="3" />
            <int name="Member2" type="uint8" defaultValue="10" bitLength="5" />
        </bitfield>
    </fields>
</schema>
----
In the example above member of the bitfield **Member1** copies all the properties
from **SomeIntField** field, then overrides its **name** and adds **bitLength**
one to specify its length in bits.

The **reuse** is allowed only from the field of the same **kind**. For example,
it is **NOT** allowed for <<fields-enum, &lt;enum&gt; >> field to reuse definition of
<<fields-int, &lt;int&gt; >>, only other <<fields-enum, &lt;enum&gt; >>.

[[fields-common-forcing-generation]]
==== Forcing Generation ====
By default the code generator is expected not to generate code for fields that
are not <<intro-references, referenced>> by any message or any other field to reduce amount of
generated code. However, there may be cases when a field releated definitions are expected
to find their way into the generated code even the field itself is not referenced
anywhere. To help with such forcing the **forceGen** <<intro-properties, property>>
has been introduced with <<intro-boolean, boolean>> value.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <int name="SomeIntField" forceGen="true" ... />
    </fields>
</schema>
----

[[fields-common-display-properties]]
==== Display Name ====
The **displayName** property is there to specify proper string of the field's
name, with spaces, dots and other characters that are not allowed to exist in
the <<intro-names, name>>.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <int name="SomeIntField" displayName="Some Int Field" ... />
    </fields>
</schema>
----

If **displayName** is not specified, the code generator must use value of property
**name** instead. In order to force empty **displayName**, use "_" (underscore) value.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <int name="SomeIntField" displayName="_" ... />
    </fields>
</schema>
----

[[fields-common-versioning]]
==== Versioning ====
**CommsDSL** allows providing an information in what version the field was added
to a particular message, as well as in what version it was deprecated, and whether
it was removed from being serialized after deprecation.

To specify the version in which field was introduced, use **sinceVersion**
property. To specify the version in which the field was deprecated, use
**deprecated** property. To specify whether the field was removed after being deprecated
use **removed** property in addition to **deprecated**.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema name="MyProtocol" endian="big" version="5" >
    <message name="SomeMessage" id="1">
        <int name="F1" type="uint16" />
        <int name="F2" type="int8" deprecated="5" />
        <int name="F3" type="uint8" sinceVersion="2" />
        <int name="F4" type="int32" sinceVersion="3" deprecated="4" removed="true" />
    </message>
</schema>
----
In the example above:

* **F1** was introduced in version **0** and hasn't been deprecated yet.
* **F2** was also introduced in version **0**, deprecated in version **5**, but **not**
removed from being serialized.
* **F3** was introduced in version **2** and hasn't been deprecated yet.
* **F4** was introduced in version **3**, deprecated in removed in version **4**.

**NOTE**, that all the specified versions mustn't be greater that the version
of the <<schema-schema, schema>>. Also value of **sinceVersion** must be
**less** than value of **deprecated**.

The version information on the field in global **&lt;fields&gt;** area or 
inside some <<intro-namespaces, namespace>> does **NOT** make sense and 
should be ignored by the code generator. It is allowed when field is a member
of a <<messages-messages, &lt;message&gt; >> or a 
<<fields-bundle, &lt;bundle&gt; >> field.

[[fields-common-failing-read-of-the-field-on-invalid-value]]
==== Failing Read of the Field on Invalid Value ====
Some fields may specify what values are considered to be valid, and there may
be a need to fail the **read** operation in case the received value is invalid.

To achieve this **failOnInvalid** property with <<intro-boolean, boolean>>
value can be used. There are two main scenarios that may require usage of this
property. One is the protocol being implemented requires such behavior in its
specification. The second is when there are multiple forms of the same message 
which are differentiated by the value of some specific field in its payload.
For example:
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema name="MyProtocol" endian="big" nonUniqueMsgIdAllowed="true" >
    <message name="Msg1Kind0" id="1" order="0">
        <int name="Kind" type="uint8" validValue="0" failOnInvalid="true" />
        ...
    </message>

    <message name="Msg1Kind1" id="1" order="1">
        <int name="Kind" type="uint8" defaultValue="1" validValue="1" failOnInvalid="true" />
        ...
    </message>

    <message name="Msg1Kind2" id="1" order="2">
        <int name="Kind" type="uint8" defaultValue="2" validValue="2" failOnInvalid="true" />
        ...
    </message>
</schema>
----
The example above defined 3 variants of the message with numeric ID equals to **1**.
When new message with this ID comes in, the <<frames-frames, framing>> code 
is expected to try reading all of the variants and choose one, on which **read** 
operation doesn't fail. The **order** property of the message specifies in
what order the messages with the same ID must be read. It described in more
detail in <<messages-messages, Messages>> chapter.

[[fields-common-pseudo-fields]]
==== Pseudo Fields ====
Sometimes there may be a need to have "psuedo" fields, which are implemented
using proper field abstration, and are handled as
any other field, but not actually getting serialized when written (or deserialized
when read). It can be achieved using **pseudo** property with <<intro-boolean, boolean>>
value.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema name="MyProtocol" endian="big" version="5" >
    <message name="SomeMessage" id="1">
        <int name="SomePseudoField" type="uint16" defaultValue="0xabcd" pseudo="true" />
        <int name="SomeRealField" type="int8">
        ...
    </message>
</schema>
----

[[fields-common-fixed-value-fields]]
==== Fixed Value (Constant) Fields ====
It is possible to disallow modification of the field's value by the client application
using **fixedValue** property with <<intro-boolean, boolean>> value.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema name="MyProtocol" endian="big" version="5" >
    <message name="SomeMessage" id="1">
        <int name="MessageVersion" type="uint8" defaultValue="1" fixedValue="true" />
        ...
    </message>
</schema>
----
In the example above the code generator must remove an ability to explicitly modify the field's value
after its construction. The field's value can still be updated by the **read** operation though.

[[fields-common-customizable-fields]]
==== Customizable Fields ====
The code generator is expected to allow some level of compile time customization of the 
generated code, such as choosing different data structures and/or adding/replacing
some runtime logic. The code generator is also expected to provide command line
options to choose required level of customization. Sometimes it may be required
to allow generated field abstraction to be customizable regardless of the customization
level requested from the code generator. **CommsDSL** provides **customizable**
property with <<intro-boolean, boolean>> value to force any field being
customizable at compile time.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <string name="SomeField" customizable="true" />
    </fields>
</schema>
----

[[fields-common-semantic-type]]
==== Semantic Type ====
Sometimes code generator may generate a bit different (or better) code for fields that are
used for some particular purpose. To specify such purpose use **semanticType**
property. 

Available semantic types are:

* **messageId** - Used to specify what type/field is used for holding numeric 
message ID. Applicable to <<fields-enum, &lt;enum&gt; >> fields.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <enum name="MsgId" type="uint8" semanticType="messageId" >
            <validValue name="Msg1" val="0x01" />
            <validValue name="Msg2" val="0x02" />
            <validValue name="Msg3" val="0x03" />
            ...
        </enum>
    </fields>
</schema>
----

* **version** - Used to specify that the field is used to hold protocol version.
Applicable to <<fields-int, &lt;int&gt; >> field (or <<fields-ref, &lt;ref&gt; >> referening
an <<fields-int, &lt;int&gt; >>).

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <int name="Version" type="uint8" semanticType="version" />
    </fields>
</schema>
----

* **length** - Used to specify that the field holds total serialization length
of the **subsequent** fields (excluding the length of the field itself).
Usually applicable to <<fields-int, &lt;int&gt; >> field
(or  <<fields-ref, &lt;ref&gt; >> referencing an <<fields-int, &lt;int&gt; >>). 
Since **v5.0** of **CommsDSL**, the **length** semantic type can be set for other
complex fields, such as <<fields-bundle, &lt;bundle&gt; >> or <<fields-bitfield, &lt;bitfield&gt; >>.
However, in such case the code generator may expect injection of custom code
(see <<fields-common-ensuring-overriding-code-injection, Ensuring Overriding Code Injection>> section below)
to override the value retrieval to make sure that the value is numeric.
In most cases the **length** semantic type is expected to be used for 
a member of <<fields-bundle, &lt;bundle&gt; >> field to limit the serialization length
of the member fields that follow.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <bundle name="CompositeField" >
            <int name="Type" type="uint8" ... />
            <int name="Length" type="uint16" semanticType="length" />
            <string name="Value" />
        </bundle>
    </fields>
</schema>
----

[[fields-common-ensuring-overriding-code-injection]]
==== Ensuring Overriding Code Injection ====
In some cases the **CommsDSL** may be insufficient to express the the protocol definition in correct way.
To handle such cases the code generator is expected to allow injection of the custom / overriding code
to fix / replace the default implementation produced by the code generator. 

The code generator is expected to generate the default code for the following operations:

* **value** - Set/Get field's value functionality.
* **read** - Reading the field's value from the input buffer.
* **write** - Writing the field's value to the output buffer.
* **refresh** - Update the field's value to a consistent state. Note, that in some composite fields 
like <<fields-bundle, &lt;bundle&gt; >>, values of internal members may depend on the values of other 
members creating the situation where the whole state may be inconsistent / incorrect. Invoking the **refresh** operation is 
expected to update the values of inner fields to bring the field into a consistent / correct state.
* **length** - Returning the serialization length of the field.
* **valid** - Returning whether the field's value is valid.
* **name** - Returning the name of the field.

To ensure visibility and/or help with forcing the injection of the correcting code, 
the **CommsDSL** provides the following <<intro-properties, properties>>.

* **valueOverride** - Control the overriding code injection for the **value** operation(s).
* **readOverride** - Control the overriding code injection for the **read** operation.
* **writeOverride** - Control the overriding code injection for the **write** operation.
* **refreshOverride** - Control the overriding code injection for the **refresh** operation.
* **lengthOverride** - Control the overriding code injection for the **length** operation.
* **validOverride** - Control the overriding code injection for the **valid** operation.
* **nameOverride** - Control the overriding code injection for the **name** operation.

The value of the <<intro-properties, properties>> above can be one of the following:

* **any** (default) - Inject the overriding code if available, use the code generated by default if not.
* **replace** - The default code is incorrect, replace it with the provided one. The code generator is expected
to report a failure in case the overriding code is unavailable.
* **extend** - The default code is still incorrect, but the code generator is expected to 
produce it (with some minor renaming to avoid names clashing) to allow reuse and extension in the overriding code. The code generator is expected
to report a failure in case the overriding code is unavailable.
* **none** - The code generator is expected to ignore the overriding code if it's available and 
produce the one generated by default instead.

[[fields-common-copying-injected-code]]
==== Copying Injected Code ====
In some cases different fields may have the **same** overriding or any other extra code that needs to be injected. In
order to minimize the copy-paste of the code, the CommsDSL introduces the 
**copyCodeFrom** property with a <<intro-references, reference>> value indicating
another field, overriding code of which needs to be applied to the field being defined.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <bundle name="CompositeField" readOverride="replace" refreshOverride="replace">
            ...
        </bundle>
        
        <bundle name="AnotherCompositeField" copyCodeFrom="CompositeField">
            ...
        </bundle>
    </fields>
</schema>
----
Note, that **copyCodeFrom** property is applied before any **xOverride**
ones described in <<fields-common-ensuring-overriding-code-injection, previous section>>.
It means that some portion of copied code can be cleared.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <bundle name="CompositeField" ... nameOverride="replace">
            ...
        </bundle>
        
        <bundle name="AnotherCompositeField" copyCodeFrom="CompositeField" nameOverride="none">
            ...
        </bundle>
    </fields>
</schema>
----

In case of <<fields-common-reusing-other-fields, reusing>> other field definition, only the field
definition properties are copied. The extra code that the original field might inject is **NOT** included
in such copy by default. The copying of injected code must be specified explicitly using
**copyCodeFrom** property descirbed above, or to avoid repetition of the
<<intro-references, reference>> string, another **reuseCode** property with
boolean value can be used in addition to **reuse** one.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <ns name="ns1">
            <bundle name="ComplexLength" valueOverride="replace" semanticType="length">
                <!-- Requires extra code for length value calculation to be injected -->
                ...
            </bitfield>

            <bitfield name="ComplexLength1" reuse="ns1.ComplexLength" copyCodeFrom="ns1.ComplexLength">
                <!-- Copies all the extra code injected to ComplexLength in addition to its properties -->
            </bitfield>

            <bitfield name="ComplexLength2" reuse="ns1.ComplexLength" reuseCode="true">
                <!-- Equivalent to ComplexLength1 -->
            </bitfield>
        </ns>
    </fields>
</schema>
----

Use <<appendix-fields, properties table>> for future references.
