[[fields-data]]
=== &lt;data&gt; Field ===
This field stores and abstracts away value of a raw bytes data. 
The **&lt;data&gt;** field has all the <<fields-common, common>> properties
as well as extra properties and elements described below.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <data name="SomeDataField" />
    </fields>
</schema>
----
Such definition of the **&lt;data&gt;** does **NOT** have any limit on
the length of the data, and will consume all the __available__ bytes in the 
input buffer. Note, that the __available__ bytes may be bound by the 
<<frames-size, &lt;size&gt; >> layer of the <<frames-frames, &lt;frame&gt; >> or 
other means. It does NOT necessarily mean that all the bytes received from the I/O link
will be consumed.

==== Default Value ====
The default value of the **&lt;data&gt;** field when constructed can be specified
using **defaultValue** <<intro-properties, property>>. The value of the
property must be case-insestive string of hexadecimal values with even number 
of characters. The allowed ranges of the characters are: [`0' - `9'], and [`a' - `f'].
The ' ' (space) character is also allowed for convenient separation of the bytes.
If not specified, defaults to empty data.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <data name="SomeDataField" defaultValue="0123 45 67 89 ab cd eF" />
    </fields>
</schema>
----
The example above is expected to create approprate raw data abstracting field, 
containing 8 bytes: [0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef] when
default constructed.

==== Fixed Length ====
In case the data value needs to be serialized using predefined fixed length,
use **length** property to specify the required value.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <data name="SomeDataField" length="16" />
    </fields>
</schema>
----

==== Length Prefix ====
Many protocols prefix raw binary data with its length. The **CommsDSL** allows definition
of such prefix using **lengthPrefix** child element, which must define prefix as
<<fields-int, &lt;int&gt; >> field.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <data name="SomeDataField">
            <lengthPrefix>
                <int name="LengthPrefix" type="uint16" />
            </lengthPrefix>
        <data>
    </fields>
</schema>
----
In case the prefix field is defined as external field, **CommsDSL** allows
usage of **lengthPrefix** as <<intro-properties, property>>, value of
which contains name of the referenced field.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <int name="DataLengthPrefix" type="uint8" />
        <data name="SomeDataField" lengthPrefix="DataLengthPrefix" />
    </fields>
</schema>
----
The **CommsDSL** also supports **detached** length prefix, when there are
several other fields in the <<messages-messages, &lt;message&gt; >> or in the
<<fields-bundle, &lt;bundle&gt; >> between the length field and the **&lt;data&gt;**.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <bundle name=SomeBundle">
            <int name="DataLengthPrefixMember" type="uint16" />
            <int name="SomeOtherFieldMember" type="uint16" />
            <data name="SomeDataFieldMember" lengthPrefix="$DataLengthPrefixMember" />
        </bundle>
    </fields>
    
    <message name="Msg1" id="1">
        <int name="DataLengthPrefix" type="uint16" />
        <int name="SomeOtherField" type="uint16" />
        <data name="SomeDataField" lengthPrefix="$DataLengthPrefix" />
    </message>
</schema>
----
**NOTE**, the existence of **$** prefix when specifying **lengthPrefix** value.
It indicates that the referenced field is a sibling in the containing
<<messages-messages, &lt;message&gt; >> or the
<<fields-bundle, &lt;bundle&gt; >> field.

The code generator is expected to take the existence of such detached prefix
into account and generate correct code for various field operations
(read, write, etc...).

**NOTE**, that **length** and **lengthPrefix** properties
are mutually exclusive, i.e. cannot be used together.


[[fields-data-valid-values]]
==== Valid Values ====
Some protocols may specify a narrow range of possible valid data values that
the field is expected to have. To specify such a valid value use **validValue**
<<intro-properties, property>>.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <data name="SomeDataField" validValue="01 02 03" />
    </fields>
</schema>
----

It is possible to provide a list of multiple valid values using child nodes.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <data name="SomeDataField">
            <validValue value="01 02 03" />
            <validValue value="aa bb cc" />
            <validValue value="12 34 56 78" />
            ...
        </data>
    </fields>
</schema>
----

It is also possible to combine a single XML attribute with other child nodes:
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <data name="SomeDataField" validValue="01 02 03">
            <validValue value="aa bb cc" />
            ...
        </data>
    </fields>
</schema>
----

When the protocol specification demands haveing a specific data value, then it is possible to
combine it with the <<fields-common-failing-read-of-the-field-on-invalid-value, failOnInvalid>>
property.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <data name="SomeDataField" validValue="01 02 03" failOnInvalid="true" />
    </fields>
</schema>
----

[[fields-data-single-valid-value]]
==== Single Valid Value ====
Sometimes the **&lt;data&gt;** field has only one valid value and it must be initialized with it. The
**defaultValidValue** <<intro-properties, property>> can be used as a replacement to the combination of
**defaultValue** and **validValue** ones having to specify the same value:
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ... version="10">
    <fields>
        <data name="SomeDataField" defaultValidValue="01 02 03" failOnInvalid="true" ... />

        <!-- Instead of:
        <data name="SomeDataField" defaultValue="01 02 03" validValue="01 02 03" failOnInvalid="true" ... />
        -->
    </fields>
</schema>
----

Use <<appendix-data, properties table>> for future references.
