[[fields-optional]]
=== &lt;optional&gt; Field ===
This field wraps other <<fields-fields, fields>> and makes the wrapped field optional, i.e.
the serialization of the latter may be skipped if it is marked as "missing".
The **&lt;optional&gt;** field has all the <<fields-common, common>> properties
as well as extra properties and elements described below.

[[fields-optional-inner-field]]
==== Inner (Wrapped) Field ====
Every **&lt;optional&gt;** must specify its inner <<fields-fields, field>>. The
wrapped field can be defined as XML child of the **&lt;optional&gt;** definition.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <optional name="SomeOptionalField">
            <int name="SomeOptionalField" type="uint32" />
        </optional>
    </fields>
</schema>
----
In case other properties of the **&lt;optional&gt;** field are defined as child
XML elements, then the element field definition needs to be wrapped by 
**&lt;field&gt;** XML child.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <optional name="SomeOptionalField">
            <displayName value="Some descriptive name" />
            <field>
                <int name="SomeOptionalField" type="uint32" />
            </field>
        </optional>
    </fields>
</schema>
----
The **CommsDSL** also allows reference of externally defined field to be
specified as inner (wrapped) field type using **field** <<intro-properties, property>>.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <int name="SomeExternalField" type="uint32" />
        <optional name="SomeOptionalField" field="SomeExternalField" />
    </fields>
</schema>
----

[[fields-optional-default-mode]]
==== Default Mode ====
Every **&lt;optional&gt;** field has 3 modes: **tenative** (default), **exist**,
and **missing**. The **exist** and **missing** modes are self explanatory. 
The **tentative** mode is there to perform *read* operation on the inner field
only if there are non-consumed bytes left in the input buffer. This mode
can be useful with protocols that just add fields at the end of the 
<<messages-messages, message>> in the new version, 
but the protocol itself doesn't report its version in any other way.

The default mode of the newly constructed **&lt;optional&gt;** field can be
specified using **defaultMode** <<intro-properties, property>>.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <optional name="SomeOptionalField" defaultMode="missing">
            <int name="SomeOptionalField" type="uint32" />
        </optional>
    </fields>
</schema>
----

[[fields-optional-existence-conditions]]
==== Existence Condition ====
Many protocols introduce optional fields, and the existence of such fields
depends on the value of some other field. Classic example would be having
some kind of flags field (see <<fields-set, **&lt;set&gt;** >>) where some bit specifies
whether other field that follows exists or not. Such conditions can be expressed
using **cond** <<intro-properties, property>>.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" id="1">
        <set name="Flags">
            <bit name="Val1Exists" idx="0" />
        </set>
        <optional name="Val1" defaultMode="missing" cond="$Flags.Val1Exists">
            <int name="ActVal1" type="uint32" />
        </optional>
    </message>
</schema>
----
**NOTE**, that **cond** property can be used only for **&lt;optional&gt;** field
that is a member of a <<fields-bundle, &lt;bundle&gt; >> or a 
<<messages-messages, &lt;message&gt; >>. The **cond** expression 
specifies condition when the **&lt;optional&gt;** field exists, and is expected to
reference other **sibling** field. Such reference is always prefixed with `$` character
to indicate that the field is a **sibling** of the **&lt;optional&gt;** and 
not some external field.

The allowed **cond** expressions are:

* $_set_field_name.bit_name_ - The wrapped field exists if specified bit is set to **true** (**1**).
* !$_set_field_name.bit_name_ - The wrapped field exists if specified bit is set to **false** (**0**).
* $_field_name_ _compare_op_ _value_ - The wrapped field exists if comparison 
of the specified field with specified value is true. The *compare_op* can be:
**=** (equality), **!=** (inequality), **&lt;** (less than), **&lt;=** (less than or equal),
**&gt;** (greater than), **&gt;=** (greater than or equal).
* $_field_name_ _compare_op_ $_other_field_name_ - The wrapped field exists if comparison 
of the specified fields is true. 

**[red]#NOTE#**, that XML doesn't allow usage of `<`
or `>` symbols in condition values directly. They need to be substituted with `\&lt;` and
`\&gt;` strings respectively.

For example:
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" id="1">
        <int name="F1" type="uint16" />
        <int name="F2" type="uint16" />
        <optional name="F3" defaultMode="exists" cond="$F1 &lt; $F2">
            <int name="WrappedF3" type="uint32" />
        </optional>
    </message>
</schema>
----
The `F3` above exists, only if value of **F1** is less than value of **F2**

Deep (nested) conditions are also expected to be supported by the code generator:
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" id="1">
        <bitfield name="F1">
            <int name="Mem1" type="uint8" bitLength="6"/>
            <set name="Mem2" bitLength="2">
                <bit name="B0" idx="0" />
                <bit name="B1" idx="1" />
            </set>
        </bitfield>
        <optional name="F2" defaultMode="missing" cond="$F1.Mem2.B0">
            <int name="WrappedF2" type="uint32" />
        </optional>
        <optional name="F3" defaultMode="exists" cond="!$F1.Mem2.B1">
            <int name="WrappedF3" type="uint32" />
        </optional>
    </message>
</schema>
----

When referencing the member of another `<optional>` field in the existence condition,
a check that the wrapping `<optional>` field **exists** in addition to the
actual specified condition is automatically implied.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" id="1">
        <set name="F1">
            <bit name="B0" idx="0" />
            <bit name="B1" idx="1" />
        </set>
        <optional name="F2" defaultMode="missing" cond="$F1.B0">
            <set name="WrappedF2">
                <bit name="B0" idx="0" />
                <bit name="B1" idx="1" />
            </set>
        </optional>
        <optional name="F3" defaultMode="exists" cond="!$F2.WrappedF2.B1">
            <int name="WrappedF3" type="uint32" />
        </optional>
    </message>
</schema>
----

Since **v6.0** of this specification referencing of the member fields of an <<interfaces-interfaces, &lt;interface&gt; >>
is also supported. Such reference is prefixed with the `%` character and it works in exactly the same way
as the reference to a sibling field described above.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <interface name="Interface">
        <bitfield name="Flags">
            <int name="Mem1" type="uint8" bitLength="6"/>
            <set name="Mem2" bitLength="2">
                <bit name="B0" idx="0" />
                <bit name="B1" idx="1" />
            </set>
        </bitfield>
    </interface>

    <message name="Msg1" id="1">
        <optional name="F1" defaultMode="missing" cond="%Flags.Mem2.B0">
            <int name="WrappedF1" type="uint32" />
        </optional>
        <optional name="F2" defaultMode="exists" cond="!%Flags.Mem2.B1">
            <int name="WrappedF2" type="uint32" />
        </optional>
    </message>
</schema>
----
**WARNING**: The **CommsDSL** specification supports multiple interfaces and doesn't impose any restriction
on how they are used in the end application. The schema parser is responsible to do
a check that **any** (not all) of the previously encountered **&lt;interface&gt;**-es contains
the referenced field. The code generator may also not impose many restrictions on such references.
Usage of the wrong **&lt;interface&gt;** class with the missing referenced
field in the end application may result in compilation errors.

Since **v6.1** of this specification comparing the size of the collection type fields (
**&lt;data&gt;**, **&lt;string&gt;**, and **&lt;list&gt;**) is also supported. The size check condition is determined
by the usage of the `#` character after the one indicating sibling (`$`) or interface (`%`) reference.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" id="1">
        <data name="F1">
            <lengthPrefix>
                <int name="Length" type="uint8" />
            </lengthPrefix>
        </data>
        <optional name="F2" defaultMode="missing" cond="$#F1 != 0">
            <int name="ActF1" type="uint32" />
        </optional>
    </message>
</schema>
----
In the example above the `F2` field exists if `F1` is not empty, i.e. its size is not `0`.

Also since **v6.1** of this specification check whether the previously encountered **&lt;optional&gt;** field
exists is also supporting in another **&lt;optional&gt;** field condition. Such check is determined by the
usage of the `?` character after the one indicating sibling (`$`) or interface (`%`) reference.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" id="1">
        <set name="F1">
            <bit name="B0" idx="0" />
            <bit name="B1" idx="1" />
        </set>
        <optional name="F2" defaultMode="missing" cond="$F1.B0">
            <set name="ActF2">
                <bit name="B0" idx="0" />
                <bit name="B1" idx="1" />
            </set>
        </optional>
        <optional name="F3" defaultMode="exists" cond="!$?F2">
            <int name="ActF3" type="uint32" />
        </optional>
    </fields>
</schema>
----
In the example above `F3` exists when `F2` is missing.

[[fields-optional-multiple-existence-conditions]]
==== Multiple Existence Conditions ====
The **CommsDSL** also allows usage of multiple existence condition statements. However,
they need to be wrapped by either **&lt;and&gt;** or **&lt;or&gt;** 
XML child elements, which represent "**and**" and "**or**" logical conditions
respectively. 
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" id="1">
        <int name="F1" type="uint16" />
        <int name="F2" type="uint16" />
        <optional name="F3" defaultMode="exists">
            <field>
                <int name="WrappedF3" type="uint32" />
            </field>
            <or>
                <cond value="$F1 = 0" />
                <and>
                    <cond value="$F1 = 1" />
                    <cond value="$F2 != 0" />
                </and>
            </or>
        </optional>
    </fields>
</schema>
----
In the example the **F3** field exists in one of the following conditions:

* Value of **F1** is 0.
* Value of **F1** is 1 and value of **F2** is not 0.

[[fields-optional-missing-on-failed-read]]
==== Missing On Failed Read ====
Some protocols may require to skip the optional field (mark it as missing) in case its read operation
fails, instead of failing the read operation of the whole message. Such functionality can be achieved
using **missingOnReadFail** <<intro-properties, property>> with <<intro-boolean, boolean>> value.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" id="1">
        ...
        <optional name="Val1" defaultMode="tentative" missingOnReadFail="true">
            <int name="ActVal1" type="uint8" validRange="[0, 10]" failOnInvalid="true" />
        </optional>
        <int name="Val2" ... />
        ...
    </fields>
</schema>
----
In the example above the `ActVal1` uses **failOnInvalid** property to fail its read operation
in case the received value is not in range `[0, 10]`. As the result the read operation of the
`Val1` field also fails. It must be marked as "missing" and
the read operation of the message must continue with reading the value of `Val2` from the same
place in the input buffer.

[[fields-optional-missing-on-invalid]]
==== Missing On Invalid ====
Similar to <<fields-optional-missing-on-failed-read, missingOnReadFail>>, but with a bit of different
flavour, the property **missingOnInvalid** insures that the **&lt;optional&gt;** field is marked as
"missing" when the held field's value is invalid (applicable to the __refresh__ operation).
In case of recognition of the invalid value
during the __read__ operation, the **&lt;optional&gt;** field must be marked as "missing" and
reading of the following fields must continue from the place in the input buffer as if the __read__
operation of the **&lt;optional&gt;** field didn't take place.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" id="1">
        ...
        <optional name="Val1" defaultMode="tentative" missingOnInvalid="true">
            <int name="ActVal1" type="uint8" validRange="[0, 10]" />
        </optional>
        <int name="Val2" ... />
        ...
    </fields>
</schema>
----

Use <<appendix-optional, properties table>> for future references.

