[[fields-string]]
=== &lt;string&gt; Field ===
This field stores and abstracts away value of a text string. 
The **&lt;string&gt;** field has all the <<fields-common, common>> properties
as well as extra properties and elements described below.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <string name="SomeStringField" />
    </fields>
</schema>
----
Such definition of the **&lt;string&gt;** does **NOT** have any limit on
the length of the string, and will consume all the __available__ bytes in the 
input buffer. Note, that the __available__ bytes may be bound by the 
<<frames-size, &lt;size&gt; >> layer of the <<frames-frames, &lt;frame&gt; >> or 
other means. It does NOT necessarily mean that all the bytes received from the I/O link
will be consumed.

[[fields-string-default-value]]
==== Default Value ====
The default value of the **&lt;string&gt;** field when constructed can be specified
using **defaultValue** <<intro-properties, property>>. If not specified, defaults to empty string.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <string name="SomeStringField" defaultValue="hello" />
    </fields>
</schema>
----

[[fields-string-fixed-length]]
==== Fixed Length ====
In case the string value needs to be serialized using predefined fixed length,
use **length** property to specify the required value.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <string name="SomeStringField" length="16" />
    </fields>
</schema>
----

[[fields-string-length-prefix]]
==== Length Prefix ====
Many protocols prefix string with its length. The **CommsDSL** allows definition
of such prefix using **lengthPrefix** child element, which must define prefix as
<<fields-int, &lt;int&gt; >> field.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <string name="SomeStringField">
            <lengthPrefix>
                <int name="LengthPrefix" type="uint8" />
            </lengthPrefix>
        <string>
    </fields>
</schema>
----
In case the prefix field is defined as external field, **CommsDSL** allows
usage of **lengthPrefix** as <<intro-properties, property>>, value of
which contains name of the <<intro-references, referenced>> field.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <int name="StringLengthPrefix" type="uint8" />
        <string name="SomeStringField" lengthPrefix="StringLengthPrefix" />
    </fields>
</schema>
----
The **CommsDSL** also supports **detached** length prefix, when there are
several other fields in the <<messages-messages, &lt;message&gt; >> or in the
<<fields-bundle, &lt;bundle&gt; >> between the length field and the **&lt;string&gt;**.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <bundle name=SomeBundle">
            <int name="StringLengthPrefixMember" type="uint8" />
            <int name="SomeOtherFieldMember" type="uint8" />
            <string name="SomeStringFieldMember" lengthPrefix="$StringLengthPrefixMember" />
        </bundle>
    </fields>
    
    <message name="Msg1" id="1">
        <int name="StringLengthPrefix" type="uint8" />
        <int name="SomeOtherField" type="uint8" />
        <string name="SomeStringField" lengthPrefix="$StringLengthPrefix" />
    </message>
</schema>
----
**NOTE**, the existence of **$** prefix when specifying **lengthPrefix** value.
It indicates that the referenced field is a sibling in the containing
<<messages-messages, &lt;message&gt; >> or the
<<fields-bundle, &lt;bundle&gt; >> field.

The code generator is expected to take the existence of such detached prefix
into account and generate correct code for various field operations
(read, write, etc...).

[[fields-string-zero-term-suffix]]
==== Zero Termination Suffix ====
Some protocols may terminate strings with **0** (zero) byte. The **CommsDSL**
support such cases with existence of **zeroTermSuffix** <<intro-properties, property>>
with <<intro-boolean, boolean>> value.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <string name="SomeStringField" zeroTermSuffix="true" />
    </fields>
</schema>
----

**NOTE**, that **length**, **lengthPrefix** and **zeroTermSuffix** properties
are mutually exclusive, i.e. cannot be used together.

[[fields-string-valid-values]]
==== Valid Values ====
Some protocols may specify a narrow range of possible valid string values that
the field is expected to have. To specify such a valid value use **validValue**
<<intro-properties, property>>.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <string name="SomeStringField" validValue="some_valid_value" />
    </fields>
</schema>
----

It is possible to provide a list of multiple valid values using child nodes.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <string name="SomeStringField">
            <validValue value="some_valid_value1" />
            <validValue value="some_valid_value2" />
            <validValue value="some_valid_value3" />
            ...
        </string>
    </fields>
</schema>
----

It is also possible to combine a single XML attribute with other child nodes:
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <string name="SomeStringField" validValue="some_valid_value1">
            <validValue value="some_valid_value2" />
            ...
        </string>
    </fields>
</schema>
----

When the protocol specification demands haveing a specific string value, then it is possible to
combine it with the <<fields-common-failing-read-of-the-field-on-invalid-value, failOnInvalid>>
property.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <string name="SomeStringField" validValue="some_required_value" failOnInvalid="true" />
    </fields>
</schema>
----

[[fields-string-single-valid-value]]
==== Single Valid Value ====
Sometimes the **&lt;string&gt;** field has only one valid value and it must be initialized with it. The
**defaultValidValue** <<intro-properties, property>> can be used as a replacement to the combination of
**defaultValue** and **validValue** ones having to specify the same value:
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ... version="10">
    <fields>
        <string name="SomeStringField" defaultValidValue="some_value" failOnInvalid="true" ... />

        <!-- Instead of:
        <string name="SomeStringField" defaultValue="some_value" validValue="some_value" failOnInvalid="true" ... />
        -->
    </fields>
</schema>
----

Use <<appendix-string, properties table>> for future references.
