
<<<
[[aliases-aliases]]
== Aliases ==
It is not uncommon for a particular field to change its meaning and as the
result to change its name over time when the protocol evolves. Simple change
of the name in the schema may result in various compilation errors of old
client code when new version of the protocol definition library is released.
To help with such case the **CommsDSL** introduces an ability to create
**alias** names for the existing fields.

For example let's assume there is some message definition like the one below:
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" id="0x1">
        <int name="SomeField" type="uint32" />
        ...
    </message>
</schema> 
----
In case there is a need to rename the **SomeField** name to be **SomeOtherField**,
then the message definition can add an **&lt;alias&gt;** with the old name to
the renamed field in order to keep the old client code compiling. 
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" id="0x1">
        <fields>
            <int name="SomeOtherField" type="uint32" />
            ...
        </fields>
        <alias name="SomeField" field="$SomeOtherField" />
    </message>
</schema> 
----
In such case the code generator must allow access of the renamed field by
both old and new names.

Note that the message fields must be bundled in **&lt;fields&gt;** XML element
in order to allow usage of non-field definition **&lt;alias&gt;** XML child of
the **&lt;message&gt;** node.

Also note that value of the **field** property of the **&lt;alias&gt;** element
must start with `$` character to indicate that the referenced field is a sibling
one, similar to <<fields-optional, &lt;optional&gt; >> field conditions.

Quite often, in order to keep protocol backward compatible, developers convert
existing numeric field into a <<fields-bitfield, &lt;bitfield&gt; >> when
need arises to add some extra field to the message. For example, let's assume
there was an enum field with limited number of valid values:
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" id="0x1">
        <enum name="SomeEnum" type="uint8">
            <validValue name="V1" val="0" />
            <validValue name="V2" val="1" />
            <validValue name="V3" val="2" />
        </enum>
        ...
    </message>
</schema> 
----
When need arises to introduce new value the developer may decide to save I/O
traffic reuse the same byte occupied by the `SomeEnum` field, like below.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" id="0x1">
        <bitfield name="F1">
            <enum name="SomeEnum" type="uint8" bitLength="2">
                <validValue name="V1" val="0" />
                <validValue name="V2" val="1" />
                <validValue name="V3" val="2" />
            </enum>
            <int name="SomeInt" type="uint8" bitLength="6" />
        </bitfield>
        ...
    </message>
</schema> 
----
In order to keep old client code compiling it is possible to introduce
alias to the `SomeEnum` member of the <<fields-bitfield, &lt;bitfield&gt; >> 
like this:
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" id="0x1">
        <fields>
            <bitfield name="F1">
                <enum name="SomeEnum" type="uint8" bitLength="2">
                    ...
                </enum>
                <int name="SomeInt" type="uint8" bitLength="6" />
            </bitfield>
            ...
        </fields>
        <alias name="SomeEnum" field="$F1.SomeEnum" />
    </message>
</schema> 
----
There can be any number of different **&lt;alias&gt;** nodes. The elements
that are allowed to have **&lt;alias&gt;**-es are <<messages-messages, &lt;message&gt; >>,
<<interfaces-interfaces, &lt;interface&gt; >>, and <<fields-bundle, &lt;bundle&gt; >>.

[[aliases-description]]
=== Description ===
The **&lt;alias&gt;** node may also have **description** 
<<intro-properties, property>> which is expected to find its way into
the generated code as a comment for the relevant access functions.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" id="1">
        ...
        <alias name="SomeField" field="SomeOtherField">
            <description>
                Some long
                multiline
                description
            </description>
        </alias>
    </message>
</schema>
----

[[aliases-reuse]]
=== Reusing Definition ===
By default when the original definition is <<fields-common-reusing-other-fields, reused>> its aliases are also copied.
It is possible to modify this default behavior by using **reuseAliases**
<<intro-properties, property>> with <<intro-boolean, boolean>> value.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <bundle name="B1">
            ...
            <alias .../>
            <alias .../>
        </bundle>

        <bundle name="B2" reuse="B1" reuseAliases="false">
            ...
        </bundle>
    </fields>
</schema>
----

[[aliases-copy]]
=== Copying Fields ===
When a new <<messages-messages, &lt;message&gt; >> or <<interfaces-interfaces, &lt;interface&gt; >> is defined, it can
copy all the fields from other already defined <<messages-messages, &lt;message&gt; >>, <<interfaces-interfaces, &lt;interface&gt; >>, or <<fields-bundle, &lt;bundle&gt; >>
(using **copyFieldsFrom** <<intro-properties, property>>).
By default all the <<aliases-aliases, &lt;alias&gt; >> definitions are also copied.
It is possible to modify this default behavior by using **copyFieldsAliases** 
<<intro-properties, property>> with <<intro-boolean, boolean>> value.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" id="1">
        ...
    </message>

    <message name="Msg2" id="2" copyFieldsAliases="false">
        ...
    </message>
    
</schema>
----

Use <<appendix-alias, properties table>> for future references.


