
<<<
[[messages-messages]]
== Messages ==
Every message is defined using **&lt;message&gt;** XML element.

[[messages-messages-message-name]]
=== Message Name ===
Every message definition must specify its <<intro-names, name>> using
**name** <<intro-properties, property>>.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" ...>
        ...
    </message>
</schema> 
----

[[messages-numeric-id]]
=== Numeric ID ===
Every message definition must specify its <<intro-numeric, numeric>> ID using
**id** <<intro-properties, property>>.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" id="0x1">
        ...
    </message>
</schema> 
----

It is highly recommended to define "message ID" numeric values as external
<<fields-enum, &lt;enum&gt; >> field and reuse its values.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <enum name="MsgId" type="uint8" semanticType="messageId">
            <validValue name="Msg1" val="0x1" />
            <validValue name="Msg2" val="0x2" />
        </enum>
    </fields>
    
    <message name="Msg1" id="MsgId.Msg1">
        ...
    </message>
    
    <message name="Msg2" id="MsgId.Msg2">
        ...
    </message>
</schema> 
----
**NOTE**, that **&lt;enum&gt;** `MsgId` is marked to contain numeric IDs of the 
messages by having `semanticType="messageId"` property assigned.

[[messages-description]]
=== Description ===
It is possible to provide a description of the message about what it is and
how it is expected to be used. This description is only for documentation
purposes and may find it's way into the generated code as a comment for the
generated class. The <<intro-properties, property>> is **description**.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" id="1">
        <description>
            Some long
            multiline
            description
        </description>
        ...
    </message>
</schema>
----

[[messages-display-name]]
=== Display Name ===
When various analysis tools display message details, the preference is to 
display proper human readable and space separated name (which is defined using **displayName**
<<intro-properties, property>>) rather than using a <<intro-names, name>>.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" id="1" displayName="Message 1">
        ...
    </message>
</schema>
----
In case **displayName** is empty, the analysis tools are expected to use value
of **name** <<intro-properties, property>> instead.

It is recommended to share the **displayName** with relevant **&lt;validValue&gt;**
of **&lt;enum&gt;** that lists numeric IDs of the messages:
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <string name="Msg1Name" defaultValue="Message 1" />
        <string name="Msg2Name" defaultValue="Message 2" />
        
        <enum name="MsgId" type="uint8" semanticType="messageId">
            <validValue name="Msg1" val="1" displayName="^Msg1Name" />
            <validValue name="Msg2" val="2" displayName="^Msg2Name" />
        </enum>
        
        <message name="Msg1" id="MsgId.Msg1" displayName="^Msg1Name">
            ...
        </message>
        
        <message name="Msg2" id="MsgId.Msg2" displayName="^Msg2Name">
            ...
        </message>
    </fields>
</schema>
----

[[messages-fields]]
=== Fields ===
Every **&lt;message&gt;** has zero or more <<fields-fields, fields>> that 
can be specified as child XML elements.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <int name="SomeCommonField" type="uint16" defaultValue="10" />
    </fields>
    
    <message name="Msg1" id="1">
        <int name="F1" type="uint8" />
        <enum name="F2" type="uint8">
            ...
        </enum>
        <ref field="SomeCommonField" name="F3" />
        <string name="F4" length="8" />
        ...
    </message>
</schema>
----
If there is any other <<intro-properties, property>> defined as XML child
of the **&lt;message&gt;**, then all the fields must be wrapped in 
**&lt;fields&gt;** XML element for separation.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema name="MyProtocol" endian="big">
    <message name="Msg1" id="1">
        <displayName value="Message 1" />
        <fields>
            <int name="F1" type="uint8" />
        </fields>
    </message>
</schema>
----

Sometimes different messages have the same fields. In order to avoid duplication,
use **copyFieldsFrom** property to specify original message.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" id="1">
        <int name="F1" type="uint32" />
    </message>
    
    <message name="Msg2" id="2" copyFieldsFrom="Msg1" />
</schema>
----
In the example above *Msg2* will have the same fields as *Msg1*. 

After copying fields from other message, all other defined fields will be
appended to copied ones.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" id="1">
        <int name="F1" type="uint32" />
    </message>
    
    <message name="Msg2" id="2" copyFieldsFrom="Msg1">
        <float name="F2" type="float" />
    </message>
</schema>
----
In the example above *Msg2* will have 2 fields: *F1* and *F2*.

Since version *4.0* of the *CommsDSL*, the *copyFieldsFrom* property allows copying
fields from the global **&lt;bundle&gt;** field as well.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <fields>
        <bundle name="B1">
            <int name="F1" type="uint32" />
            <int name="F2" type="uint16" />
        </bundle>
    </fields>
    
    <message name="Msg1" id="1" copyFieldsFrom="B1">
        <int name="F3" type="uint16" />
    </message>
</schema>
----
In the example above *Msg1* will have 3 fields: *F1*, *F2*, and *F3*.

It is also possible to replace some of the fields after copying using 
**&lt;replace&gt;** child node.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" id="1">
        <int name="F1" type="uint32" />
        <int name="F2" type="uint8" />
    </message>
    
    <message name="Msg2" id="2" copyFieldsFrom="Msg1">
        <replace>
            <enum name="F2" type="uint8">
                <validValue name="V0" val="0" />
                <validValue name="V1" val="1" />
            </enum>
        </replace>
    </message>
</schema>
----
The replacing field must have the same name as the copied member field it is
replacing. The **&lt;replace&gt;** child node may have multiple member fields replacing
the copied ones. The order of the fields inside the **&lt;replace&gt;** child node
is not important, the order of the fields is determined by the original 
**&lt;message&gt;** or **&lt;bundle&gt;** field, member fields of which were
copied.

It is possible to combine **&lt;replace&gt;**-ing copied fields and extending
the **&lt;message&gt;** with new fields. 
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" id="1">
        <int name="F1" type="uint32" />
        <int name="F2" type="uint8" />
    </message>
    
    <message name="Msg2" id="2" copyFieldsFrom="Msg1">
        <replace>
            <enum name="F2" type="uint8">
                <validValue name="V0" val="0" />
                <validValue name="V1" val="1" />
            </enum>
        </replace>
        <fields>
            <int name="F3" type="uint16" />
        </fields>
    </message>
</schema>
----

The example above is equivalent to defining `Msg2` **&lt;message&gt;**
in the following way.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema name="MyProtocol" endian="big">
    <message name="Msg2" id="2">
        <int name="F1" type="uint32" />    
        <enum name="F2" type="uint8">
            <validValue name="V0" val="0" />
            <validValue name="V1" val="1" />
        </enum>
        <int name="F3" type="uint16" />
    </message>
</schema>
----

[[messages-ordering]]
=== Ordering ===
There are protocols that may define various forms of the same message, 
which share the same numeric ID, but are differentiated by a serialization 
length or value of some particular
field inside the message. It can be convenient to define such variants as separate
classes. In case there are multiple **&lt;message&gt;**-es with the same
<<messages-numeric-id, numeric ID>>, it is required to specify order 
in which they are expected to be processed (read). The ordering is specified
using **order** <<intro-properties, property>> with unsigned <<intro-numeric, numeric>>
value. The message object with lower **order** value gets created and its
*read* operation attempted **before** message object with higher value.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema name="MyProtocol" nonUniqueMsgIdAllowed="true">
    <message name="Msg1Form1" id="1" order="0" >
        ...
    </message>
    
    <message name="Msg1Form2" id="1" order="1">
        ...
    </message>    
</schema>
----
**NOTE** that there is a need to set **nonUniqueMsgIdAllowed** property of
the <<schema-schema, schema>> to **true** to allow multiple message objects
with the same numeric ID.

All the **order** values for the same numeric ID must be unique, but not necessarily
sequential.

[[messages-versioning]]
=== Versioning ===
**CommsDSL** allows providing an information in what version the message was added
to the protocol, as well as in what version it was deprecated, and whether
it was removed (not supported any more) after deprecation.

To specify the version in which message was introduced, use **sinceVersion**
property. To specify the version in which the message was deprecated, use
**deprecated** property. To specify whether the message was removed after being deprecated
use **removed** property in addition to **deprecated**.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema name="MyProtocol" endian="big" version="5" >
    <message name="SomeMessage" id="100" sinceVersion="2" >
        ...
    </message>

    <message name="SomeOtherMessage" id="101" sinceVersion="3" deprecated="4" removed="true">
        ...
    </message>
    
</schema>
----
In the example above *SomeMessage* was introduced in version *2*, and 
*SomeOtherMessage* was introduced in version *3*, but deprecated and removed in
version *4*.

**NOTE**, that all the specified versions mustn't be greater that the version
of the <<schema-schema, schema>>. Also value of **sinceVersion** must be
**less** than value of **deprecated**.

The code generator is expected to be able to generate support for specific versions
and include / exclude support for some messages based on their version information.

=== Platforms ===
Some protocols may be used in multiple independent platforms, while having 
some platform-specific messages. The **CommsDSL** allows listing of the
supported platforms using <<intro-platforms, &lt;platform&gt; >> XML nodes.
Every message may list platforms in which it must be supported using **platforms**
<<intro-properties, property>>. In case the property's value is empty (default),
the message is supported in **all** the available platforms (if any defined).
The **platforms** property value is coma-separated list of platform names with
preceding **+** if the listed platforms are the one supported, or **-** if 
the listed platforms need to be **excluded** from all available ones.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <platform name="Plat1" />
    <platform name="Plat2" />
    <platform name="Plat3" />
    <platform name="Plat4" />
    
    <message name="Msg1" id="1" platforms="+Plat1,Plat4">
        ...
    </message>
    
    <message name="Msg2" id="2" platforms="-Plat1, Plat2">
        ...
    </message>
</schema> 
----
In the example above *Msg1* is supported only for platforms *Plat1* and *Plat4*,
while *Msg2* is **NOT** supported in *Plat1*, and *Plat2* (i.e. supported in
*Plat3* and *Plat4*).

The main consideration for what format to choose should be whether the platforms 
support for the message should or should **NOT** be added automatically when
new **&lt;platform&gt;** is defined.

[[messages-sender]]
=== Sender ===
In most protocols there are uni-directional messages. The **CommsDSL**
allows definition of entity that sends a particular message using **sender**
property. Available values are **both** (default), **server**, and **client**.
The code generator may use provided information and generate some auxiliary code
and/or data structures to be used for *client* and/or *server* implementation.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" id="1" sender="client">
        ...
    </message>
    
    <message name="Msg2" id="2" sender="server">
        ...
    </message>

    <message name="Msg3" id="2">
        ...
    </message>
</schema> 
----
In the example above *Msg1* and *Msg2* are uni-directional messages, while
*Msg3* is bi-directional.

[[messages-message-length-validation]]
=== Message Length Validation ===
Many protocol specifications provide expected serialization length of the message. In order to
prevent various typos or copy-paste errors, the **CommsDSL** provides an ability to 
validate the specified message length during the schema file parsing. To perform such a 
check use **validateMinLength** <<intro-properties, property>> with <<intro-numeric, unsigned>> value.
It can help to avoid some copy-paste or typo errors
at the time of schema parsing rather than debugging generated incorrect code.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" validateMinLength="6" ...>
        <int name="F1" type="uint32" />
        <int name="F2" type="uint16" />
    </message>
</schema> 
----

[[messages-customization]]
=== Customization ===
The code generator is expected to allow some level of compile time customization of the 
generated code, such as enable/disable generation of particular virtual functions. 
The code generator is also expected to provide command line
options to choose required level of customization. Sometimes it may be required
to allow generated message class to be customizable regardless of the customization
level requested from the code generator. **CommsDSL** provides **customizable**
property with <<intro-boolean, boolean>> value to force any message to being
customizable at compile time.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" id="1" validateMinLength="6">
        <int name="F1" type="uint32" />
        <int name="F2" type="int16" />
        <optional name="F3" defaultMode="exist">
            <int name="F3Field" type="uint8" />
        </optional>
    </message>
</schema>
----
Note, that <<fields-optional, &lt;optional&gt; >> field is always expected to have 0 minimal length regardless
of its <<fields-optional-existence-conditions, existence conditions>>.

Also note, that the value of **validateMinLength** is the expected serialization length of
message fields __without__ the fields of the <<frames-frames, &lt;frame&gt; >>.

[[messages-alias-to-fields]]
=== Alias Names to Member Fields ===
Sometimes an existing member field may be renamed and/or moved. It is possible to
create alias names for the fields to keep the old client code being able to compile
and work. Please refer to <<aliases-aliases, Aliases>> chapter for more details.

[[messages-ensuring-overriding-code-injection]]
=== Ensuring Overriding Code Injection  ===
Similar to <<fields-common-ensuring-overriding-code-injection, fields>> the default code
generation for the <<messages-messages, &lt;message&gt; >> definition may be incomplete or incorrect. The code generator 
is expected to allow injection of the overriding code to allow replacing or extension of 
the default one.

The code generator is expected to produce the same operations / functionality as with fields (excluding **value**).

* **read** - Reading all the message fields from the input buffer.
* **write** - Writing all the message fields to the output buffer.
* **refresh** - Bringing message fields to a consistent state. Note, that values of some member fields 
may depend on the values of other ones creating the situation where the whole state may be inconsistent / incorrect. 
Invoking the **refresh** operation is 
expected to update the values of member fields to bring the message contents into a consistent / correct state.
* **length** - Returning the serialization length of the message fields.
* **valid** - Returning whether values of all the message fields are valid.
* **name** - Returning the name of the message.

The same
overriding control properties can be apply to the <<messages-messages, &lt;message&gt;-s>>
(**readOverride**, **writeOverride**, **refreshOverride**, **lengthOverride**, **validOverride**,
and **nameOverride**) with the same values (**any**, **replace**, **extend**, **none**).

[[messages-copying-injected-code]]
=== Copying Injected Code ===
In some cases different messages may have the **same** overriding or other extra code that needs to be injected. In
order to minimize the copy-paste of the code, the CommsDSL introduces the 
**copyCodeFrom** property with a <<intro-references, reference>> value indicating
another message, overriding code of which needs to be applied to the message being defined.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" readOverride="replace" refreshOverride="replace">
        ...
    </message>
        
    <message name="Msg2" copyCodeFrom="Msg1">
            ...
    </message>
</schema>
----
Note, that **copyCodeFrom** property is applied before any **xOverride**
ones described in <<messages-ensuring-overriding-code-injection, previous section>>.
It means that some portion of copied code can be cleared.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" ... nameOverride="replace">
        ...
    </message>
        
    <message name="Msg2" copyCodeFrom="Msg1" nameOverride="none">
            ...
    </message>
</schema>
----

[[messages-construct-requirements]]
=== Extra Construction Requirements ===
In some cases the message object construction may require updating
fields in its <<interfaces-interfaces, &lt;interface&gt; >>. The
**CommsDSL** provides such an ability using the **construct** property.
The reference to the interface field is performed using the same syntax
as with the <<fields-optional, &lt;optional&gt; >> field's <<fields-optional-existence-conditions, existence conditions>>,
i.e. using `%` prefix.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <interface name="Interface">
        <bitfield name="Flags">
            <set name="Bits" bitLength="4">
                <bit name="B0" idx="0" />
                <bit name="B1" idx="1" />
            </set>
            <int name="Extra" type="uint8" bitLength="4" />
        </bitfield>
    </interface>

    <message name="Msg1" ... construct="%Flags.Bits.B0">
        ...
    </message>

    <message name="Msg2" ... construct="%Flags.Extra = 2">
        ...
    </message>

</schema>
----

In the example above `Msg1` constructor must set `Flags.Bits.B0` bit, while `Msg2`
constructor must assign `2` to the `Flags.Extra` field.

To perform multiple updates to the interface fields the `<construct>` child node with its single `<and>` child node must be used.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <interface name="Interface">
        <bitfield name="Flags">
            <set name="Bits" bitLength="4">
                <bit name="B0" idx="0" />
                <bit name="B1" idx="1" />
            </set>
            <int name="Extra" type="uint8" bitLength="4" />
        </bitfield>
    </interface>

    <message name="Msg1" ...>
        <construct>
            <and>
                <construct value="%Flags.Bits.B0">
                <construct value="!%Flags.Bits.B1">
                <construct value="%Flags.Extra = 1">
            </and>
        </construct>
        <fields>
            ...
        </fields>
    </message>
</schema>
----
The `<construct>` nodes are very similar to the `<cond>` ones used to describe multiple
<<fields-optional-existence-conditions, existence conditions>> of the <<fields-optional, &lt;optional&gt; >>
field, but with some limitations:

- Only bit sets and equality statements are supported.
- Only `<and>` nodes are supported.

**WARNING**: The **CommsDSL** specification supports multiple interfaces and doesn't impose any restriction
on how they are used in the end application. The schema parser is responsible to do
a check that **any** (not all) of the previously encountered **&lt;interface&gt;**-es contains
the referenced field. The code generator may also not impose many restrictions on such references.
Usage of the wrong **&lt;interface&gt;** class with the missing referenced
field in the end application may result in compilation errors.

[[messages-read-conditions]]
=== Extra Read Conditions ===
The **read** operation of every <<messages-messages, &lt;message&gt; >> means invoking
the **read** operation for every one of its member fields. However, there may be cases
when preliminary evaluation of the <<interfaces-interfaces, &lt;interface&gt; >> fields
needs to be performed. To do so the **readCond** property referencing appropriate
<<interfaces-interfaces, &lt;interface&gt; >> fields can be used. The syntax is
the same as with the <<fields-optional, &lt;optional&gt; >> field's <<fields-optional-existence-conditions, existence conditions>>.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <interface name="Interface">
        <bitfield name="Flags">
            <set name="Bits" bitLength="4">
                <bit name="B0" idx="0" />
                <bit name="B1" idx="1" />
            </set>
            <int name="Extra" type="uint8" bitLength="4" />
        </bitfield>
    </interface>

    <message name="Msg1" ... readCond="!%Flags.Bits.B1">
        ...
    </message>

    <message name="Msg2" ...>
        <readCond>
            <or>
                <readCond value="%Flags.Bits.B0">
                <and>
                    <readCond value="!%Flags.Bits.B1">
                    <readCond value="%Flags.Extra = 1">
                </and>
            </or>
        </readCond>
        <fields>
            ...
        </fields>
    </message>
</schema>
----
In case of multiple conditions the **readCond** needs to be specified
as the `<readCond>` child node with a single `<and>` or `<or>` immediate child.
Nested `<and>` and/or `<or>` conditions are allowed in the same way as with the
<<fields-optional, &lt;optional&gt; >> field's <<fields-optional-existence-conditions, existence conditions>>.
The only difference is that the inner child nodes must be named `readCond` instead of `cond`.

Quite often the <<messages-read-conditions>> (**readCond**) are the same as the <<messages-construct-requirements>> (**construct**).
To avoid unnecessary statements duplication there is **constructAsReadCond** property with
<<intro-boolean, boolean>> value to force copying **construct** value(s) to the **readCond**.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <interface name="Interface">
        <bitfield name="Flags">
            <set name="Bits" bitLength="4">
                <bit name="B0" idx="0" />
                <bit name="B1" idx="1" />
            </set>
            <int name="Extra" type="uint8" bitLength="4" />
        </bitfield>
    </interface>

    <message name="Msg1" ... constructAsReadCond="true">
        <construct>
            <and>
                <construct value="%Flags.Bits.B0">
                <construct value="!%Flags.Bits.B1">
                <construct value="%Flags.Extra = 1">
            </and>
        </construct>
        <fields>
            ...
        </fields>
    </message>
</schema>
----
It is equivalent to
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <interface name="Interface">
        <bitfield name="Flags">
            <set name="Bits" bitLength="4">
                <bit name="B0" idx="0" />
                <bit name="B1" idx="1" />
            </set>
            <int name="Extra" type="uint8" bitLength="4" />
        </bitfield>
    </interface>

    <message name="Msg1" ...>
        <construct>
            <and>
                <construct value="%Flags.Bits.B0">
                <construct value="!%Flags.Bits.B1">
                <construct value="%Flags.Extra = 1">
            </and>
        </construct>
        <readCond>
            <and>
                <readCond value="%Flags.Bits.B0">
                <readCond value="!%Flags.Bits.B1">
                <readCond value="%Flags.Extra = 1">
            </and>
        </readCond>
        <fields>
            ...
        </fields>
    </message>
</schema>
----

[[messages-valid-conditions]]
=== Extra Validity Conditions ===
The **valid** operation of every <<messages-messages, &lt;message&gt; >> means invoking
the **valid** operation for every one of its member fields. However, the valid values
of fields may be interdependent. There may be a need to introduce extra validity checks
on the message contents. To do so the **validCond** property referencing appropriate
<<interfaces-interfaces, &lt;interface&gt; >> fields and/or fields of the
<<messages-messages, &lt;message&gt; >> itself can be used. The syntax is
the same as with the <<fields-optional, &lt;optional&gt; >> field's
<<fields-optional-existence-conditions, existence conditions>>.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <interface name="Interface">
        <bitfield name="Flags">
            <set name="Bits" bitLength="4">
                <bit name="B0" idx="0" />
                <bit name="B1" idx="1" />
            </set>
            <int name="Extra" type="uint8" bitLength="4" />
        </bitfield>
    </interface>


    <message name="Msg1" ... validCond="!%Flags.Bits.B1">
        ...
    </message>
</schema>
----

In case of multiple conditions the **validCond** needs to be specified
as the `<validCond>` child node with a single `<and>` or `<or>` immediate child.
Nested `<and>` and/or `<or>` conditions are allowed in the same way as with the
<<fields-optional, &lt;optional&gt; >> field's <<fields-optional-existence-conditions, existence conditions>>.
The only difference is that the inner child nodes must be named `validCond` instead of `cond`.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <interface name="Interface">
        <bitfield name="Flags">
            <set name="Bits" bitLength="4">
                <bit name="B0" idx="0" />
                <bit name="B1" idx="1" />
            </set>
            <int name="Extra" type="uint8" bitLength="4" />
        </bitfield>
    </interface>


    <message name="Msg1" ... >
        <fields>
            <int name="F1" type="uint8" />
            <int name="F2" type="uint8" />
        </fields>
        <validCond>
            <and>
                <validCond value="!%Flags.Bits.B1" />
                <or>
                    <validCond value="$F1 = 0" />
                    <validCond value="$F2 != F1" />
                </or>
            </and>
        </validCond>
    </message>
</schema>
----

Quite often the <<messages-valid-conditions>> (**validCond**) are the same as the <<messages-construct-requirements>> (**construct**).
To avoid unnecessary statements duplication there is **constructAsValidCond** property with
<<intro-boolean, boolean>> value to force copying **construct** value(s) to the **validCond**, similar
to the **constructAsReadCond** property described <<messages-read-conditions, above>>.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <interface name="Interface">
        <bitfield name="Flags">
            <set name="Bits" bitLength="4">
                <bit name="B0" idx="0" />
                <bit name="B1" idx="1" />
            </set>
            <int name="Extra" type="uint8" bitLength="4" />
        </bitfield>
    </interface>

    <message name="Msg1" ... constructAsValidCond="true">
        <construct>
            ...
        </construct>
        <fields>
            ...
        </fields>
    </message>
</schema>
----

[[messages-fail-read-on-invalid]]
=== Failing Read on Invalid Contents ===
In the <<messages-valid-conditions, previous section>> it was shown that the `<message>`
can have extra conditions for its payload to be valid. Sometimes these extra conditions are
required to be taken into account during the **read** operation and the latter should
fail in case the message contents are invalid. To support such case the
**failOnInvalid** <<intro-properties, property>> with boolean value should be used
(the same way as with <<fields-common-failing-read-of-the-field-on-invalid-value, fields>>).

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" ... failOnInvalid="true">
        <fields>
            <int name="F1" type="uint8" />
            <int name="F2" type="uint8" />
        </fields>
        <validCond>
            <or>
                <validCond value="$F1 = 0" />
                <validCond value="$F2 != F1" />
            </or>
        </validCond>
    </message>
</schema>
----

The **failOnInvalid** property for the `<message>` can also be used to fail the **read** operation in
case any of the member fields has an invalid value.


[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" ... failOnInvalid="true">
        <int name="F1" type="uint8" validRange="[0, 10]" />
    </message>
</schema>
----

[[messages-reusing-other-fields]]
=== Reusing Other Messages ===
Sometimes two different messages are very similar but differ in one or two particular aspects. It is possible
to reuse the other message definition using **reuse** property (similar to <<fields-common-reusing-other-fields, fields>>),
especially when things like <<messages-construct-requirements, construction requirements>>,
<<messages-read-conditions, read conditions>>, and <<messages-valid-conditions, validity conditions>> need
to be copied.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg1" ...>
        <construct>
        </construct>
        <readCond>
        </readCond>
        <fields>
            ...
        </fields>
    </message>

    <message name="Msg2" reuse="Msg1" ...>
        <!-- Added fields -->
        ...
    </message>
</schema>
----
Similar to using the <<messages-fields, copyFieldsFrom>> property any new fields defined are added to ones
copied from the **reuse**-d message.

In case of reusing other message definition, only the message
definition properties are copied. The extra code that the original message might inject is **NOT** included
in such copy by default. The copying of injected code must be specified explicitly using
<<messages-copying-injected-code, copyCodeFrom>> property described above, or to avoid repetition of the
<<intro-references, reference>> string, another **reuseCode** property with
boolean value can be used in addition to **reuse** one.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <message name="Msg2" reuse="Msg1" reuseCode="true" ...>
        ...
    </message>
</schema>
----

Use <<appendix-message, properties table>> for future references.

