[[frames-checksum]]
=== &lt;checksum&gt; Layer ===
The **&lt;checksum&gt;** layer represents checksum bytes, usually (but not always) 
present at the end of the <<frames-frames, frame>>. 
[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema endian="big" ...>
    <frame name="ProtocolFrame">
        <sync name="Sync">
            ...
        </sync>
        <size name="Size">
            ...
        </size>
        <id name="Id">
            ...  
        </id>
        <payload name="Data" />
        <checksum name="Checksum" ...>
            <int name="ChecksumField" type="uint16" />
        </checksum>
    </frame>
</schema>
----
The **&lt;checksum&gt;** layer has all the <<frames-common, common>> properties
as well as extra properties and elements described below.

[[frames-checksum-algorithm]]
==== Checksum Algorithm ====
The checksum calculation algorithm must be specified using **alg**
<<intro-properties, property>>. Supported values are:

* **sum** - Sum of all the bytes.
* **xor** - Exclusive OR (XOR) of all the bytes.
* **crc-ccitt** (aliases: **crc_ccitt**) - https://en.wikipedia.org/wiki/Cyclic_redundancy_check[CRC-16-CCITT]
where polynomial is `0x1021`, initial value is `0xffff`, final XOR value is `0`, and no reflection of bytes.
* **crc-16** (aliases: **crc_16**) - https://en.wikipedia.org/wiki/Cyclic_redundancy_check[CRC-16-IBM],
where polynomial is `0x8005`, initial value is `0`, final XOR value is `0`, reflection is performed on every
byte as well as final value.
* **crc-32** (aliases: **crc_32**) - https://en.wikipedia.org/wiki/Cyclic_redundancy_check[CRC-32],
where polynomial is `0x04C11DB7`, initial value is `0xffffffff`, final XOR value is `0xffffffff`, reflection is
performed on every byte as well as final value.
* **custom** - Custom algorithm, code for which needs to be provided to the
code generator, so it can copy it to the generated code.

[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema endian="big" ...>
    <frame name="ProtocolFrame">
        ...
        <payload name="Data" />
        <checksum name="Checksum" alg="crc-16" ...>
            <int name="ChecksumField" type="uint16" />
        </checksum>
    </frame>
</schema>
----

When **custom** algorithm is selected, its name must be provided using 
**algName** property.
[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema endian="big" ...>
    <frame name="ProtocolFrame">
        ...
        <payload name="Data" />
        <checksum name="Checksum" alg="custom" algName="MyCustomChecksumCalc" ...>
            <int name="ChecksumField" type="uint16" />
        </checksum>
    </frame>
</schema>
----
The provided name of the custom algorithm can be used by the code generator
to locate the required external implementation file and use appropriate 
class / function name when the calculation functionality needs to be invoked.

[[frames-checksum-calculation-area]]
==== Calculation Area ====
The **checksum** layer definition must also specify the layers, data of which is
used to calculate the checksum. It is done using **from** property that is
expected to specify name of the layer where checksum calculation starts.
[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema endian="big" ...>
    <frame name="ProtocolFrame">
        <sync name="Sync">
            ...
        </sync>
        <size name="Size">
            ...
        </size>
        <id name="Id">
            ...  
        </id>
        <payload name="Data" />
        <checksum name="Checksum" alg="crc-16" from="Size">
            <int name="ChecksumField" type="uint16" />
        </checksum>
    </frame>
</schema>
----
The example above defines `SYNC | SIZE | ID | PAYLOAD | CHECKSUM` frame where
the checksum is calculated on `SIZE` + `ID` + `PAYLOAD` bytes.

Some protocols may put checksum value as prefix to the area on which the
checksum needs to be calculated. In this case use **until** property (instead
of **from**) to specify layers for checksum calculation.
[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema endian="big" ...>
    <frame name="ProtocolFrame">
        <sync name="Sync">
            ...
        </sync>
        <size name="Size">
            ...
        </size>
        <id name="Id">
            ...  
        </id>
        <checksum name="Checksum" alg="crc-16" until="Data">
            <int name="ChecksumField" type="uint16" />
        </checksum>
        <payload name="Data" />
    </frame>
</schema>
----

[[frames-checksum-verification-order]]
==== Checksum Verification Order ====
The default behavior of the **&lt;checksum&gt;** layer is to perform calculation
after all relevant layers and their fields have been successfully read and
processed. However, it is possible to
force the checksum verification right away (without reading fields of other layers
and/or message payload).
It is usually possible to do when value of the <<frames-size, &lt;size&gt; >> field
is already processed, so the right location of checksum value is known, 
and it is not included in checksum calculation. To force immediate checksum
verification use **verifyBeforeRead** <<intro-properties, property>> with
<<intro-boolean, boolean>> value.
[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema endian="big" ...>
    <frame name="ProtocolFrame">
        <sync name="Sync">
            ...
        </sync>
        <size name="Size">
            ...
        </size>
        <id name="Id">
            ...  
        </id>
        <checksum name="Checksum" alg="crc-16" until="Data" verifyBeforeRead="true">
            <int name="ChecksumField" type="uint16" />
        </checksum>
        <payload name="Data" />
    </frame>
</schema>
----
**WARNING**: Incorrect use of **verifyBeforeRead** <<intro-properties, property>> can be dangerous especially
for the cases when the **&lt;checksum&gt;** follows **&lt;payload&gt;**. The 
order of framing layers processing is NOT pre-determined, it's up to the code generator to choose. In cases when
**&lt;checksum&gt;** covers the **&lt;size&gt;** in its checksum calculation area and the **verifyBeforeRead** property
value is set to **true**, the checksum calculation happens right away assuming that the checksum value is located 
__at the end of the input buffer__ rather than bound by the value of the **&lt;size&gt;** layer field.
[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema endian="big" ...>
    <frame name="ProtocolFrame">
        <sync name="Sync">
            ...
        </sync>
        <size name="Size">
            ...
        </size>
        <id name="Id">
            ...  
        </id>
        <payload name="Data" />
        
        <!-- Incorrect and dangerous -->
        <checksum name="Checksum" alg="crc-16" from="Size" verifyBeforeRead="true">
            <int name="ChecksumField" type="uint16" />
        </checksum>        
    </frame>
</schema>
----
Such assumption is obviously incorrect when stream communication I/O link is used (like RS-232 or TCP/IP) and multiple 
as well as partial messages can reside in the input buffer at the same time. However, in cases like
datagram communication I/O link (like UDP/IP) when the messages are received in full and processed one by one,
the assumption of having checksum value location at the end of the input
buffer may be correct.

The bottom line, set the **verifyBeforeRead** property value only when you know what you're doing. 
It's an optimization feature in vast majority of cases.
Make the code work correctly without it first and only add it to improve runtime performance.

Use <<appendix-checksum, properties table>> for future references.
