[[frames-custom]]
=== &lt;custom&gt; Layer ===
The **&lt;custom&gt;** layer represent any other protocol specific layer, 
functionality of which cannot be implemented using other provided layers.
The code generator must allow injection of the externally implemented code
of the layer functionality when generating code relevant to the 
transport <<frames-frames, framing>>.
[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema endian="big" ...>
    <frame name="ProtocolFrame">
        <size name="Size">
            ...
        </size>
        <custom name="SomeCustomLayer">
            <int name="SomeField" type="uint8" />
        </custom>
        <id name="Id">
            ...  
        </id>
        <payload name="Data" />
    </frame>
</schema>
----

The **&lt;value&gt;** layer has all the <<frames-common, common>> properties
as well as extra properties and elements described below.

[[frames-custom-semantic-layer-type]]
==== Semantic Layer Type ====
In most cases the **&lt;custom&gt;** layer is used to replace one of the layers
specified earlier, default implementation / definition of which doesn't provide
the necessary functionality. To provide the code generator with the purpose of
the **&lt;custom&gt;** layer use **semanticLayerType** property.

[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema endian="big" ...>
    <frame name="ProtocolFrame">
        <size name="Size">
            ...
        </size>
        <custom name="IdAndFlags" semanticLayerType="id">
            <bitfield name="IdAndFlagsField">
                <int name="Id" type="uint16" bitLength="12" />
                <set name="Flags" bitLength="4">
                    ...
                </set>
            </bitfield>
        </custom>
        <payload name="Data" />
    </frame>
</schema>
----

The value of the **semanticLayerType** property is one of the supported layers
covered in this chapter: **payload**, **id**, **size**, **sync**, **checksum**, 
**value**, and **custom** (default).

Such meta-information may help with the correct code generation and reduce amount of 
custom code injection (or eliminate it altogether).

[[frames-custom-replacing-checksum-layer]]
==== Replacing &lt;checksum&gt; Layer ====
The <<frames-checksum, &lt;checksum&gt; >> layer requires specification of the
<<frames-checksum-calculation-area, area>> on which the checksum is calculated. 
It is performed using **from** or **until** properties. When **&lt;custom&gt;**
layer replaces **&lt;checksum&gt;** (by using `semanticLayerType="checksum"`), 
such area is specified using **checksumFrom** or **checksumUntil** properties.

[source, xml]
----
<schema endian="big" ...>
    <frame name="ProtocolFrame">
        <size name="Size">
            ...
        </size>
        <id name="Id">
            ...
        </id>
        <payload name="Data" />
        <custom name="Checksum" semanticLayerType="checksum" checksumFrom="Size">
            <int name="ChecksumField" type="uint16" />
        </custom>
    </frame>
</schema>
----


Use <<appendix-custom, properties table>> for future references.
