[[frames-size]]
=== &lt;size&gt; Layer ===
The **&lt;size&gt;** layer represents **remaining** serialization length of the
<<frames-frames, frame>> until the end of message frame (with some caveats).
The <<frames-frames, frame>> definition must **NOT** contain more
than one **&lt;size&gt;** layer.
[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <frame name="ProtocolFrame">
        <size name="Size">
            <int name="SizeField" type="uint16" />
        </size>
        <id name="Id">
            <int name="IdField" type="uint8" />
        </id>
        <payload name="Data" />
    </frame>
</schema>
----
Some protocols may specify that the field of the **&lt;size&gt;** layer
contains its own length as well. The **CommsDSL** allows implementation of
such case by adding usage of **serOffset** property to the field of the
**&lt;size&gt;** layer.
[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <frame name="ProtocolFrame">
        <size name="Size">
            <int name="SizeField" type="uint16" serOffset="2" displayOffset="2"/>
        </size>
        <id name="Id">
            <int name="IdField" type="uint8" />
        </id>
        <payload name="Data" />
    </frame>
</schema>
----

The example below implements `ID (2 bytes) | SIZE (2 bytes) | PAYLOAD` framing
where `SIZE` value includes length of the header (`ID` + `SIZE`) in addition to
the length of `PAYLOAD`.
[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <frame name="ProtocolFrame">
        <id name="Id">
            <int name="IdField" type="uint16" />
        </id>
        <size name="Size">
            <int name="SizeField" type="uint16" serOffset="4" displayOffset="4"/>
        </size>
        <payload name="Data" />
    </frame>
</schema>
----
There are protocols that append extra fields (such as <<frames-checksum, &lt;checksum&gt; >>) after the payload.
Depending on whether the **&lt;size&gt;** layer itself is included in the checksum calculation the usage of the
**serOffset** property might be required. For example, when checksum covers **&lt;size&gt;**'s value in
its calculation (using **from** property) the usage of **serOffset** is required.
[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <frame name="ProtocolFrame">
        <size name="Size">
            <int name="SizeField" type="uint16" serOffset="2" displayOffset="2"/>
        </size>
        <id name="Id">
            <int name="IdField" type="uint8" />
        </id>
        <payload name="Data" />
        <checksum ... from="Size">
            <!-- Covers Size -->
            <int name="ChecksumField" type="uint16" />
        </checksum>
    </frame>
</schema>
----

However, in case the **&lt;size&gt;**'s value is not covered in the checksum calculation such settings are not required.
[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <frame name="ProtocolFrame">
        <size name="Size">
            <int name="SizeField" type="uint16"/>
        </size>
        <id name="Id">
            <int name="IdField" type="uint8" />
        </id>
        <payload name="Data" />
        <checksum ... from="Payload">
            <!-- Does not cover Size -->
            <int name="ChecksumField" type="uint16" />
        </checksum>
    </frame>
</schema>
----
The right conceptual model here should be: If the layer after the **&lt;payload&gt;** covers **&lt;size&gt;** in its **from** property, then it falls out from
the automatic **remaining** bytes calculation and must be accounted for with the **serOffset** and **displayOffset** properties
adjustments.

The **&lt;size&gt;** layer doesn't have
any extra properties in addition to <<frames-common, common>> ones.
