
<<<
[[interfaces-interfaces]]
== Interfaces ==
There are protocols that attach some extra information, such as version and/or
extra flags, to the message transport <<frames-frames, framing>>. This extra information
usually influences how message fields are deserialized and/or how message object
is handled. It means that these received extra values need to be attached to
**every** message object. The **CommsDSL** allows specification of such extra
information as **&lt;interface&gt;** XML element with extra <<fields-fields, fields>>.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <interface name="CommonInterface">
        <int name="Version" type="uint8" semanticType="version" />
        <set name="Flags" length="1">
            ...
        </set>
    </interface>
</schema> 
----
The code generator may use provided information to generate common interface
class(es) for all the messages. Such class will serve as base class of every
message object and will contain required extra information.

**NOTE** that specified fields, are **NOT** part of every message's payload.
These fields are there to hold extra values delivered as part of message 
<<frames-frames, framing>>.

[[interfaces-name]]
=== Interface Name ===
Every interface definition must specify its <<intro-names, name>> using
**name** <<intro-properties, property>>.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <interface name="CommonInterface">
        ...
    </interface>
</schema> 
----

[[interfaces-description]]
=== Description ===
It is possible to provide a description of the interface about what it is and
how it is expected to be used. This description is only for documentation
purposes and may find it's way into the generated code as a comment for the
generated class. The <<intro-properties, property>> is **description**.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <interface name="CommonInterface">
        <description>
            Some long
            multiline
            description
        </description>
        ...
    </interface>
</schema>
----

[[interfaces-fields]]
=== More About Fields ===
Similar to **&lt;message&gt;** every **&lt;interface&gt;** has zero or more <<fields-fields, fields>> that 
can be specified as child XML elements. If there is any other 
<<intro-properties, property>> defined as XML child
of the **&lt;interface&gt;**, then all the fields must be wrapped in 
**&lt;fields&gt;** XML element for separation.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema name="MyProtocol" endian="big">
    <interface>
        <name value="CommonInterface" />
        <fields>
            <int name="Version" type="uint8" semanticType="version" />
        </fields>
    </interface>
</schema>
----

Sometimes different interfaces have common set of fields. In order to avoid duplication,
use **copyFieldsFrom** property to specify original interface and then add
extra fields when needed.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <interface name="Interface1">
        <int name="Version" type="uint8" semanticType="version" />
    </interface>
    
    <interface name="Interface2" copyFieldsFrom="Interface1">
        <set name="Flags" length="1">
            ...
        </set>
    </interface>
</schema>
----
In the example above *Interface2* will have **2** fields: "Version" and "Flags". 

Since version *4.0* of the *CommsDSL* the *copyFieldsFrom* property allows copying
fields  from the global **&lt;bundle&gt;** field as well.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <bundle name="B1">
        <int name="Version" type="uint8" semanticType="version" />
        <set name="Flags" length="1">
            ...
        </set>        
    </bundle>
        
    <interface name="Interface1" copyFieldsFrom="B1" />
</schema>
----

If the protocol doesn't have any extra values delivered in message framing, then
the whole definition of the  **&lt;interface&gt;** XML element can be omitted.
If no **&lt;interface&gt;** node has been added to the protocol schema, then 
the code generator must treat schema as if the schema has implicit definition
of the single **&lt;interface&gt;** with no fields. It is up to the code generator
to choose name for the common interface class it creates.

**NOTE** usage of **semanticType="version"** for the field holding protocol
version in the examples above. It is required to be used for proper 
<<versioning-versioning, protocol versioning>>. The value of the field
having "version" value as **semanticType** property, will be considered 
for fields that, were introduced and/or deprecated at some stage, i.e. use
**sinceVersion** and/or **derecated** + **removed** properties.

[[interfaces-alias-names]]
=== Alias Names to Fields ===
Sometimes a contained field may be renamed and/or moved. It is possible to
create alias names for the fields to keep the old client code being able to compile
and work. Please refer to <<aliases-aliases, Aliases>> chapter for more details.

[[interfaces-reusing-other-fields]]
=== Reusing Other Interfaces ===
Sometimes two different interfaces are very similar but differ in one or two particular aspects. It is possible
to reuse the other interface definition using **reuse** property (similar to <<fields-common-reusing-other-fields, fields>>
and <<messages-reusing-other-fields, messages>>).
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <interface name="Interface1" ...>
        ...
    </interface>

    <interface name="Interface2" reuse="Interface1" ...>
        <!-- Added fields -->
        ...
    </interface>
</schema>
----
Similar to using the <<interfaces-fields, copyFieldsFrom>> property any new fields defined are added to ones
copied from the **reuse**-d interface.

In case of reusing other interface definition, only the interface
definition properties are copied. The extra code that the original interface might inject is **NOT** included
in such copy by default. To include injected code use **reuseCode** property with
boolean value can be used in addition to **reuse** one.
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<schema ...>
    <interface name="Interface2" reuse="Interface1" reuseCode="true" ...>
        ...
    </interface>
</schema>
----


Use <<appendix-interface, properties table>> for future references.
